# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab787f2e9d5f470f0779544c7a36a64630e4402458952b6dbdbbd6b32faea38f53b4bcd4bff79a67ff71fbd0340bf8543475293f22d93f8b80523da9aaf083a5

test:
  secret_key_base: 1ef82cceaec777a756ae09749d0a466eecdbd2b387733c8a8e8b9603de036ca348868bf5335481c7dde2b81b936ac7cc4a35ad4991337f9548272e60e019c315

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
